### PR TITLE
New settings menu ui

### LINKED ISSUE #219: Automatic backups options don't fit on screen
### Steps to reproduce

1. Open the app
2. Go to settings

### Expected behavior

It should not be aligned vertically.

### Actual behavior

The last option for automatic backups (Both) is aligned vertically because there is no space. And in english there is no text.

### Connect You version

6.0

### Android version

Android 13

### Other details

Screenshot_20230816_230057_Connect You

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by M00NJ**
I worked on the settings menu. I used switches, dividers and reordered the settings into three instead of four categories. This redesign should close #219 (I can't test it, since I cannot reproduce it). I also did the Android Gradle plugin upgrade like we talked about. I hope this doesn't break anything for you ;). The settings menu now has the same spacing values etc. like I used in ClockYou, to bring the apps closer together. I have two ideas to improve the UX some more and would like to get your opinion on them:

1. I think it would make more sense (and also definitely fix #219 for good) if we replaced the "none" option in the automatic backup preference by a switch.  The user can then turn automatic backup on/off first and only if turned on, choose what to back up. If turned off, we could hide or grey out the rest, which makes the menu less cluttered. This was also in the mockup I made some time ago, so I'll paste it here so you can see what I mean...

247185541-16c97717-154e-495f-9ce1-ff365c19afc2

2. I would simplify the strings of the two buttons at the bottom: "Choose directory" -> "Directory" and "Password for backup" -> "Password", since I think their position makes it self explanatory and they should be more concise. I didn't do this already, because I don't know what this will mean for the translation.

Here is how the menu looks so far:

Before:
Screenshot_20230818-125026

After: 
Screenshot_20230818-125002

### CODE REVIEW

**Comment by Bnyro** [comment]
1. I think that's a good idea, but we shouldn't add the switch directly to the category title `Backup` (the one in purple in the design draft), but rather into a separate preference below, since categories shouldn't be able to become disabled.
2. That's fine, you can just modify the string. They will be marked as "outdated" for all other languages on Weblate, so that translators can change them from time to time, which is fine for our case I think. If the new strings were completely different, you could also remove the currently used strings for all languages via Android Studio's translations editor, and add new ones with different keys, so that users see the English string if not yet translated, instead of the old one.

I myself am still not sure about the new design of the option to select the start tab - I'd like to hear what @SuhasDissa thinks about that (in the first screenshot).

**Comment by SuhasDissa** [comment]
I personally prefer moving each setting item into a separate screen.

Take [Seal](https://github.com/JunkFood02/Seal) for example.

They have the most organized setting screen I've ever seen.

**Comment by Bnyro** [comment]
We currently only have very few options - so placing each category in its own tab seems a bit like an overkill to me.

**Comment by SuhasDissa** [comment]
IMO that amount of settings deserve seperate screens. Its better not only for looks but also for accessibility reasons.

Just try to use settings screen with "Talk back" turned on.

**Comment by M00NJ** [comment]
> 1. I think that's a good idea, but we shouldn't add the switch directly to the category title `Backup` (the one in purple in the design draft), but rather into a separate preference below, since categories shouldn't be able to become disabled.

Yes, the  switch should turn the "automatic backup" option on or off, not the hole category. I would combine this with animated visibility, so everything after that is hidden, when automatic backup is switches off. Greying out would also be an option, but hiding it completely is probably cleaner.

> 2. That's fine, you can just modify the string. They will be marked as "outdated" for all other languages on Weblate, so that translators can change them from time to time, which is fine for our case I think. 

Alright, I will go with that option then :)

> I myself am still not sure about the new design of the option to select the start tab

I can leave this like it is now. I would like to use checkboxes instead of the segmented button for the automatic backup category though. The M3D guidelines recommend checkboxes, whenever two options can be selected at the same time, which is the case here. This would remove the "both" button and leave us with just two checkboxes, "device" and "local". Very clean and consice ;)

**Comment by M00NJ** [comment]
> I personally prefer moving each setting item into a separate screen.

I agree with Bnyro here. I don't think we have enough options to warrent separate screens for each category.  There are also advantages to having everything visible on one screen. However when the app matures and the settings screen gets longer, I'd prefer separate screens as well...

**Comment by SuhasDissa** [comment]
> However when the app matures and the settings screen gets longer, I'd prefer separate screens as well...

Yes I agree 👍🏻

**Comment by Bnyro** [comment]
https://github.com/you-apps/ConnectYou/pull/222/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R7: Looks like you accidentally included a Gradle update too here: I'm fine with these changes, but please move them to a different commit, since that's not related to the design changes.

**Comment by SuhasDissa** [comment]
Replace the gradle files with the original and do a new commit.

Then do a fixup.

It will combine two or more commits into one.

**Comment by M00NJ** [comment]
> Replace the gradle files with the original and do a new commit.
> 
> Then do a fixup.
> 
> It will combine two or more commits into one.

Can you tell me the commands? I've never done this before...

**Comment by SuhasDissa** [comment]
Do it in android studio

Create new commit with original gradle files.

Goto 'Git' tab in android studio and rightclick the commit and select fixup.

**Comment by SuhasDissa** [comment]
Sorry, I missed a step there.

You need to right click the commit before the new commit and select "Intractively rebase from here"

Then a window will popup. In that window right click the latest commit and select fixup.

**Comment by M00NJ** [comment]
> Sorry, I missed a step there.
> 
> You need to right click the commit before the new commit and select "Intractively rebase from here"
> 
> Then a window will popup. In that window right click the latest commit and select fixup.

Damn, I already followed the steps and was wondering why the fixup doesn't work 😬.
Is there a way to go back, or should I just push the new commit now?

**Comment by SuhasDissa** [comment]
image

Here I fixup the "improve pan and zoom"

After the fixup both commits work as one

image

**Comment by SuhasDissa** [comment]
> Damn, I already followed the steps and was wondering why the fixup doesn't work 😬. Is there a way to go back, or should I just push the new commit now?

Sorry, that's my fault.

If nothing is messed up then push it. If something doesn't look good then you better reset your local git repo and retry doing the changes

**Comment by M00NJ** [comment]
> Sorry, that's my fault.

No worries, I screwed up on my part as well... 

It doesn't look right, so I'll need to do a reset. Just tried `git reset --hard origin/master`, but it won't let me. It's saying `fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.` Is it looking for the commit to revert it, but cannot find if because of the fixup? I'm really so to have to bother you with this again. I'm new to git (and apparently not good at it) :/

**Comment by M00NJ** [comment]
> > Damn, I already followed the steps and was wondering why the fixup doesn't work 😬. Is there a way to go back, or should I just push the new commit now?
> 
> @M00NJ The best thing to do is to push your changes to a new branch of your fork So we all can look what went wrong and fix it

That's a good idea, I'll do that. Thank's for your support!

**Comment by SuhasDissa** [comment]
> It doesn't look right, so I'll need to do a reset. Just tried `git reset --hard origin/master`, but it won't let me. It's saying `fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.` Is it looking for the commit to revert it, but cannot find if because of the fixup? I'm really so to have to bother you with this again. I'm new to git (and apparently not good at it) :/

You need to use the name of the remote branch instead of `master`

in this case

``` bash
git fetch origin/new-settings-menu-ui
git reset --hard origin/new-settings-menu-ui
```

**Comment by M00NJ** [comment]
It created a new branch in my fork: https://github.com/M00NJ/ConnectYou/tree/i-messed-up
I think I did the fixup with the wrong commit...

**Comment by SuhasDissa** [comment]
@M00NJ Here's the fixed repo.

[ConnectYou.zip](https://github.com/you-apps/ConnectYou/files/12398135/ConnectYou.zip)

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
Lgtm!

Please **squash and merge** this PR via the GitHub UI, to keep our commit log clean :)

**Comment by M00NJ** [comment]
> Please **squash and merge** this PR via the GitHub UI, to keep our commit log clean :)

Looks like I don't have write access here

**Comment by Bnyro** [comment]
Oh, that should be fixed now.

**Pull request merged**
