### PR TITLE
feat: Support for storing SMS privately inside the app

### LINKED ISSUE #269: Private SMS database
### Describe your suggested feature

Just like private contacts, I'd like to propose private SMS db instead of system SMS storage.

Why?
The benefit is simple… so many bank/payments apps, that force user to allow SMS read(and/or write) permission, scrap all conversations including financial transactions, personal chats and OTPs and use this to profile and target users with ads. This feature will hopefully put an end to this.

How?
This does not seem as simple as adding local contacts. I imagine sending and receiving SMS normally, copying it in local db and then clearing the system storage each time might work.

Anyway thanks for all the work. Just throwing an idea out if it seems feasible. 

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
### This is not yet tested!

closes #269

cc @Surendrajat

If you have time, please test the debug builds from this PR.

### CODE REVIEW

**Comment by SuhasDissa** [comment]
The app initially worked fine, but crashed on subsequent messages.
A notification appeared for every message received, but only the first message was saved.

#### Error Log:
```
FATAL EXCEPTION: main
Process: com.bnyro.contacts.debug, PID: 7437
java.lang.RuntimeException: Unable to start receiver com.bnyro.contacts.receivers.SmsReceiver: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: localSms.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4315)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: localSms.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.kt:102)
	at com.bnyro.contacts.db.dao.LocalSmsDao_Impl$4.call(LocalSmsDao_Impl.java:89)
	at com.bnyro.contacts.db.dao.LocalSmsDao_Impl$4.call(LocalSmsDao_Impl.java:84)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
	at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

#### Database:
image

**Comment by Bnyro** [comment]
That's strange, the ID should be auto generated in theory: 
see https://github.com/you-apps/ConnectYou/pull/271/files#diff-e83903797c4bc2d62832233b3cee52661788f1fd870ae355ec25fd322e4e62f8R9.

Not sure what's going on here, thanks for testing however.

**Comment by Surendrajat** [comment]
@Bnyro tested it and found two issues:
1. Can't see any old msgs after enabling `Private SMS database`
2. Encountered this crash when tried to send a msg:
```
FATAL EXCEPTION: main
Process: com.bnyro.contacts.debug, PID: 20410
java.lang.NullPointerException: {
            context.ge…er::class.java)
        } must not be null
	at com.bnyro.contacts.util.SmsUtil.getSmsManager(SmsUtil.kt:33)
	at com.bnyro.contacts.util.SmsUtil.sendSms(SmsUtil.kt:47)
	at com.bnyro.contacts.ui.models.SmsModel$sendSms$1$sms$1.invokeSuspend(SmsModel.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@adb2a8, Dispatchers.Main.immediate]
```

Thanks for the quick PR.

**Comment by Bnyro** [comment]
1. is the intended behavior - the messages you previously received will stay in the devices Sms database.

**Comment by Bnyro** [comment]
> The app initially worked fine, but crashed on subsequent messages.
> A notification appeared for every message received, but only the first message was saved.
>
Should be fixed now.

**Comment by Surendrajat** [comment]
> 1. is the intended behavior - the messages you previously received will stay in the devices Sms database.

Can there be a way to replicate sms history inside this app too? I don't mind clearing old sms from phone manually after that.

**Comment by julianfairfax** [comment]
Should this not be a separate app? If you're building an SMS app, you should release an SMS app, rather than put it into a contacts app.

**Comment by M00NJ** [comment]
> Should this not be a separate app? If you're building an SMS app, you should release an SMS app, rather than put it into a contacts app.

No, we're trying to take a more modern approach by combining features that evolve around the same category, in this case communication. ConnectYou might also see a dialer tab one day (That's not a promise). It's more convenient for the users, because they don't have to switch between apps and also more convenient for us, because one app is easier to maintain than two.

**Comment by julianfairfax** [comment]
> It's more convenient for the users, because they don't have to switch between apps

I disagree. Apps are not supposed to do many things at once, but be good at the things they do. Every SMS and phone app for Android is separate. It is not hard for a user. Why would it be? You can click a little icon in your contacts to message or phone someone, or select a contact to message or phone from the messaging or phone app. No one is going to be like managing their contacts, messaging people, and calling them all at the same time. These should be different apps.

> and also more convenient for us, because one app is easier to maintain than two.

I can almost guarantee you that isn't going to be the case. Once you put everything in a big monolithic repository, you'll have a much harder time working on stuff. It's much easier to just keep developing Connect You as it is, which is a contacts app. If you insist on making a messaging app, you will have to write most of the code as new anyway. Maybe you can reuse the contacts code, but you'll only need to select contacts, so a simple list view would suffice, rather than a manager.

**Comment by M00NJ** [comment]
> Every SMS and phone app for Android is separate. 

You kinda gave the answer yourself there. Every "SMS or phone app", but this is not that. Look at Messenger apps like signal. They have messages, voice calls, video calls, etc. all combined in one app and it makes it very convenient.

> I can almost guarantee you that isn't going to be the case. 

That's for us to decide here. I for myself have no issue dealing with more files in a project. It doesn't make it harder to find anything. Apart from that I much rather do one release than two. Again convenience.

> If you insist on making a messaging app, you will have to write most of the code as new anyway. 

Bnyro already implemented the SMS feature and it's already released. 

I think this is enough for a explanation on why we decided to go about it this way. How and what features we implement is not up to debate.

**Comment by julianfairfax** [comment]
> Bnyro already implemented the SMS feature and it's already released.

Sorry, I didn't realise that.

**Pull request merged**
