### PR TITLE
Combine Local and Device contacts into a single tab

### PR DESCRIPTION
**Pull request by SuhasDissa**

### CODE REVIEW

**Review by M00NJ — APPROVED** [review]

**Comment by Bnyro** [comment]
Code lgtm, two UI nitpicks
1. I don't really like the divider/line below the search bar - I'd prefer removing it.
2. Please add some horizontal and top margin to the expanded search bar.

**Comment by SuhasDissa** [comment]
Btw I think it would be better to save the last used source as a preference instead of having a dedicated setting for that.

**Comment by Bnyro** [comment]
Might make sense to change that in the future, prior to this PR the preference has probably the better change.

You can do it with this PR already if you want.

**Review by Bnyro — APPROVED** [review]

**Comment by M00NJ** [comment]
> Btw I think it would be better to save the last used source as a preference instead of having a dedicated setting for that.

Agreed. It's always good to keep the settings as clean as possible.

**Pull request merged**
