### PR TITLE
Shared vcard importing support  ( closes #244 )

### LINKED ISSUE #244: Display as option when sharing vcf files
### Describe your suggested feature

Seems like it is possible to be displayed in android share menu depending on the file type. ConnectYou should be displayed when sharing vcf file as "import to ConnectYou".

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**

### CODE REVIEW

**Comment by Bnyro** [comment]
I think the OP also wants us to support `android.intent.action.SEND` for sharing the vcf file to the app, instead of using the "open with" dialog.
(We can use the already existing logic for handling the vcf intent for that)

**Comment by SuhasDissa** [comment]
Yea, I had to read the issue again to realize that. LoL.
I thought he wanted to have some additional text like "Import to ConnectYou"

**Comment by Bnyro** [comment]
Yeah, sometimes I struggle understanding issue descriptions too...

**Comment by Bnyro** [comment]
That change is not bad either though :)

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
