### PR TITLE
feat: show call disconnect status

### PR DESCRIPTION
**Pull request by SuhasDissa**
Wondering if there's a way to make the alert dialog fit the material you theme

### CODE REVIEW

**Comment by Bnyro** [comment]
We can probably start activities from the broadcast receiver? If so, we can start a new activity like in https://github.com/you-apps/TranslateYou/pull/429.

**Comment by SuhasDissa** [comment]
I was thinking of using a boolean value in the activity to trigger a jetpack compose alert dialog

**Comment by Bnyro** [comment]
Hmm, we can probably use a `MutableLiveData<Boolean>` for that purpose?

**Comment by SuhasDissa** [comment]
> Hmm, we can probably use a `MutableLiveData<Boolean>` for that purpose?

mutableState will also work

**Pull request merged**
