### PR TITLE
Sms list and threads design changes

### PR DESCRIPTION
**Pull request by Bnyro**
(The changes are explained in the commit messages.)

see #292 
see #293

### CODE REVIEW

**Comment by SuhasDissa** [comment]
Profile photos are looking a bit weird
image

**Comment by M00NJ** [comment]
Nice!
Two ideas I had for the chat screen
- add a call button to the top right
- display the date when the message was sent once above the messages, instead of in every message to avoid the same date being displayed everywhere like in the screenshot (and maybe just display yesterday instead of the date, when it was sent only a day ago)

signal-2023-10-11-20-15-19-277

**Review by M00NJ — APPROVED** [review]

**Comment by Bnyro** [comment]
> Profile photos are looking a bit weird image
>
My bad, should be fixed now :+1:

**Comment by SuhasDissa** [comment]
> My bad, should be fixed now 👍
Nope

image

**Comment by Bnyro** [comment]
> Nice! Two ideas I had for the chat screen
> 
> add a call button to the top right
> 
> display the date when the message was sent once above the messages, instead of in every message to avoid the same date being displayed everywhere like in the screenshot (and maybe just display yesterday instead of the date, when it was sent only a day ago)
> 
1. I agree that this is a good idea :+1:
2. I don't think that's really a good idea since we display something like "20 minutes ago" if the message is very recent. So we might want to group by date too and display it additionally as you suggested, but we should still keep the date + time per message too imo.

**Comment by Bnyro** [comment]
> Nope
> 
> image
>

Ohh, I see what's going on...

**Comment by M00NJ** [comment]
> 2. I don't think that's really a good idea since we display something like "20 minutes ago" if the message is very recent. So we might want to group by date too and display it additionally as you suggested, but we should still keep the date + time per message too imo.

Take a look at Signal, it handles it pretty well IMO. It groups messages by date, displays the time in the messages or "20m", etc. if it's very recent. Having the date in every message makes the bubbles bigger and the ui more cluttered.

**Pull request merged**
